// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Uck9_X5QnlkVhRB1YMM6n2TbOChN7DA',
    appId: '1:619813651822:web:129019930686751751ed7f',
    messagingSenderId: '619813651822',
    projectId: 'loginapp-49d63',
    authDomain: 'loginapp-49d63.firebaseapp.com',
    storageBucket: 'loginapp-49d63.appspot.com',
    measurementId: 'G-PHRFZDQ406',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3MpQgU0ses1dCnVy3qCLjv4xzcftEzxc',
    appId: '1:619813651822:android:fcb7d61b59a198b351ed7f',
    messagingSenderId: '619813651822',
    projectId: 'loginapp-49d63',
    storageBucket: 'loginapp-49d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7D68-zI_lAucN2V4oU6DjR9JtVbs8ZE',
    appId: '1:619813651822:ios:1383aa5164b6a2f251ed7f',
    messagingSenderId: '619813651822',
    projectId: 'loginapp-49d63',
    storageBucket: 'loginapp-49d63.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7D68-zI_lAucN2V4oU6DjR9JtVbs8ZE',
    appId: '1:619813651822:ios:bdb4d244068f96da51ed7f',
    messagingSenderId: '619813651822',
    projectId: 'loginapp-49d63',
    storageBucket: 'loginapp-49d63.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
